### ISSUE TITLE
Не хватает аннотации @Serializable

### ISSUE THREAD

**Issue by DenisPavlov** [otuskotlin/202012-otuskotlin-marketplace#4]
https://github.com/otuskotlin/202012-otuskotlin-marketplace/blob/2cb0e1864964780779f284616e5d904f5bc39984/ok-marketplace-mp-transport-mp/src/commonMain/kotlin/ru/otus/otuskotlin/marketplace/transport/kmp/models/common/ResponseStatusDto.kt#L3

**Comment by svok** [comment]
Исправил
